#!/bin/bash
#PBS -q normal
#PBS -j oe
#PBS -l walltime=00:00:30,mem=4GB
#PBS -l wd
#PBS -l ncpus=48

module load openmpi intel-compiler intel-mkl

# example small values
N=2000
wT=32

opts='"" -e -x'
opts="-r -b" 
opts='""'

ps='12 24 48' # note that for $p<48, we still pay for all ncpus=48!!

for opt in $opts ; do
    if [ "$opt" = '""' ] ; then
	opt=
    fi
    for p in $ps; do	
	echo ""
	echo mpirun -np $p ./testCholesky $opt $N $wT
	time mpirun -np $p ./testCholesky $opt $N $wT
    done
done

if [ ! -z "$PBS_NODEFILE" ] ; then
   cat $PBS_NODEFILE
fi

exit
